yvoronoy/m2install

- m2install.sh
Please check and merge my pull request. 
Thank you.
> FIX-1: Added recursive find for config file up to root directory

- m2install.sh
> Added possibility to install Magento from the scratch

- m2install.sh
> Changed askValue method

- m2install.sh
> Added composerInstall method

- m2install.sh
Changed gitClone method: CE deploys into current directory
> Changed gitClone method: CE deploys into current directory

- m2install.sh
Added parsing command line arguments
> Added parsing command line arguments

- m2install.sh
> Changed printUsage method

- m2install.sh
Added printGitConfirmation method
> Added printGitConfirmation method

- m2install.sh
> Clean admin/url/use_custom after deploy

- m2install.sh
> Check dependencies function

- m2install.sh
Fix if statement in generateDBName()
> Fix if statement in generateDBName()

- m2install.sh
A few optimizations and fix for #74
> A few optimizations

- .travis.yml
- tests/env/osx_dependencies.sh
- tests/functional/deploy.sh
> Add testing on OS X platform

- m2install.sh
array changed to short syntax from array() to []
2.2.4 restore dumps doesn't work
Fix by using PHP code to generate env.php
> Fix #141: Dumps deployment fails on 2.2.4

- m2install.sh
> Fix #144 filter in getTablePrefix()

- README.md
- m2install.sh
Added B2B section to the documentation
> Added B2B support to wizard installer

- m2install.sh
Changed file structure for website subfolder and app directory list init.
> Websites entrypoint fix

- m2install.sh
- install from composer
- LS in desabled by default after m2install
> Support for LiveSearch:

- .github/workflows/functional-tests.yml
- m2install.sh
Reverts yvoronoy/m2install#183
> Revert "Shell Check"

- m2install.sh
Fixed the default value assignment for BIN_PHP.
> Fixed default value for PHP variable

- m2install.sh
I added more keys to delete during the installation.
> Deleting Payment Services config
